### ISSUE TITLE
collision_avoidance.py无法运行

### ISSUE THREAD

**Issue by Heritagecll** [hanruihua/ir_sim#10]
似乎是在添加图形元素时使用了不正确的坐标，报错信息如下
User
Traceback (most recent call last):
  File "/home/c/RL_nav/ir_sim-main/ir_sim/usage/11collision_avoidance/collision_avoidance.py", line 8, in <module>
    env.render(0.01)
  File "/home/c/RL_nav/ir_sim-main/ir_sim/env/env_base.py", line 118, in render
    self._env_plot.draw_components('dynamic', self.objects, **kwargs)
  File "/home/c/RL_nav/ir_sim-main/ir_sim/env/env_plot.py", line 78, in draw_components
    [obj.plot(self.ax, **kwargs) for obj in objects if not obj.static]
  File "/home/c/RL_nav/ir_sim-main/ir_sim/env/env_plot.py", line 78, in <listcomp>
    [obj.plot(self.ax, **kwargs) for obj in objects if not obj.static]
  File "/home/c/RL_nav/ir_sim-main/ir_sim/world/robots/robot_diff.py", line 55, in plot
    super().plot(ax, show_goal=show_goal, show_arrow = show_arrow, **kwargs)
  File "/home/c/RL_nav/ir_sim-main/ir_sim/world/object_base.py", line 483, in plot
    self.plot_trail(ax, **self.plot_kwargs)
  File "/home/c/RL_nav/ir_sim-main/ir_sim/world/object_base.py", line 596, in plot_trail
    ax.add_patch(car_circle)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1971, in add_patch
    self._update_patch_limits(p)
  File "/usr/lib/python3/dist-packages/matplotlib/axes/_base.py", line 1991, in _update_patch_limits
    xys = patch.get_patch_transform().transform(vertices)
  File "/usr/lib/python3/dist-packages/matplotlib/patches.py", line 1505, in get_patch_transform
    self._recompute_transform()
  File "/usr/lib/python3/dist-packages/matplotlib/patches.py", line 1493, in _recompute_transform
    self._patch_transform = transforms.Affine2D() \
  File "/usr/lib/python3/dist-packages/matplotlib/transforms.py", line 1970, in translate
    translate_mtx = np.array(
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 3) + inhomogeneous part.
Simulated Environment End with sim time elapsed: 0.2 seconds

**Comment by hanruihua** [comment]
这个可能是 numpy 版本的问题， 可以升级到最新版试试， 如果还是有报错, 可以提供一下环境，例如python 和 numpy的版本
